import { Product } from './types';

export const PRODUCTS: Record<string, Product> = {
  // ── Diet ────────────────────────────────────────────
  d1: {
    id: 'd1', category: 'diet', emoji: '🍚',
    name: '오뚜기 현미밥 24개입',
    tagline: '혈당 천천히 올리는 통곡물 즉석밥',
    reason: '정제 탄수화물 대신 현미로 혈당 스파이크를 줄여드려요',
    price: '18,900원', priceNum: 18900,
    originalPrice: '23,000원', discountRate: 18,
    coupangUrl: 'https://www.coupang.com/np/search?q=오뚜기+현미밥+24개',
    keyBenefit: '요리 없이 혈당 관리까지',
    detailReason: '즉석밥이지만 현미 비율 50%로 GI 지수가 낮아 혈당 급등을 방지합니다. 바쁜 1인 가구도 전자레인지 90초면 건강한 한 끼 완성.',
  },
  d2: {
    id: 'd2', category: 'diet', emoji: '🥗',
    name: '닭가슴살 샐러드 밀키트',
    tagline: '고단백 저지방, 체중 관리의 정석',
    reason: '포만감 높고 칼로리 낮아 체중 관리에 최적이에요',
    price: '9,800원', priceNum: 9800,
    originalPrice: '12,000원', discountRate: 18,
    coupangUrl: 'https://www.coupang.com/np/search?q=닭가슴살+샐러드+밀키트',
    keyBenefit: '한 끼로 단백질 30g 채우기',
    detailReason: '닭가슴살 120g + 채소 혼합으로 단백질 30g, 칼로리 350kcal. 체중 증가 시 점심을 이 한 끼로 교체하면 주당 약 0.3kg 감량 효과를 기대할 수 있어요.',
  },
  d3: {
    id: 'd3', category: 'diet', emoji: '🌾',
    name: '저당 그래놀라 500g',
    tagline: '혈당 스파이크 없는 아침 식사',
    reason: '설탕 최소화 + 식이섬유 풍부로 혈당 조절에 도움',
    price: '12,500원', priceNum: 12500,
    originalPrice: '15,000원', discountRate: 17,
    coupangUrl: 'https://www.coupang.com/np/search?q=저당+그래놀라+무가당',
    keyBenefit: '설탕 3g 이하, 식이섬유 8g',
    detailReason: '일반 그래놀라 대비 당 함량 70% 낮추고 식이섬유로 포만감을 유지합니다. 혈당 전당뇨 범위라면 아침 식사를 이걸로 교체해보세요.',
  },
  d4: {
    id: 'd4', category: 'diet', emoji: '🥣',
    name: '퀵 오트밀 30봉',
    tagline: 'β-글루칸으로 콜레스테롤·혈압 동시 관리',
    reason: '수용성 식이섬유가 혈압과 혈중 콜레스테롤을 낮춰줘요',
    price: '14,900원', priceNum: 14900,
    originalPrice: '18,000원', discountRate: 17,
    coupangUrl: 'https://www.coupang.com/np/search?q=퀵오트밀+무가당',
    keyBenefit: '혈압 관리에 임상 증거 있는 식품',
    detailReason: '오트밀의 β-글루칸은 혈압을 평균 4~5mmHg 낮추는 것으로 알려져 있습니다. 혈압 주의 범위라면 아침마다 이걸로 시작하세요.',
  },
  d5: {
    id: 'd5', category: 'diet', emoji: '🥜',
    name: '혼합 견과류 데일리 30봉',
    tagline: '오메가3·마그네슘·불포화지방 한 봉에',
    reason: '견과류 속 마그네슘이 혈압 조절과 스트레스 완화를 도와요',
    price: '16,900원', priceNum: 16900,
    originalPrice: '21,000원', discountRate: 20,
    coupangUrl: 'https://www.coupang.com/np/search?q=혼합견과류+데일리팩+30봉',
    keyBenefit: '하루 한 봉, 심혈관 건강 루틴',
    detailReason: '아몬드·호두·캐슈넛 조합으로 오메가3 및 마그네슘 일일 권장량 20% 이상 충족. 소분 포장이라 집순이도 간편하게 챙길 수 있어요.',
  },

  // ── Essentials ──────────────────────────────────────
  e1: {
    id: 'e1', category: 'essential', emoji: '⚖️',
    name: '샤오미 스마트 체중계',
    tagline: '체중·체지방·근육량 앱으로 한눈에',
    reason: '매일 측정하면 건강 관리 의지력이 2배 높아져요',
    price: '29,900원', priceNum: 29900,
    originalPrice: '39,000원', discountRate: 23,
    coupangUrl: 'https://www.coupang.com/np/search?q=샤오미+스마트체중계',
    keyBenefit: '체지방·근육량까지 측정',
    detailReason: 'BMI와 체지방률을 수치로 보면 다이어트 효과가 훨씬 빠르게 나타납니다. 앱 연동으로 이 앱에 기록해두면 주간 트렌드를 자동 분석해드려요.',
  },
  e2: {
    id: 'e2', category: 'essential', emoji: '💊',
    name: '오므론 자동 혈압계',
    tagline: '병원급 정확도를 집에서',
    reason: '혈압은 아침 기상 직후 측정이 가장 정확해요',
    price: '49,900원', priceNum: 49900,
    originalPrice: '68,000원', discountRate: 27,
    coupangUrl: 'https://www.coupang.com/np/search?q=오므론+자동혈압계',
    keyBenefit: '아침 루틴으로 고혈압 조기 감지',
    detailReason: '혈압은 측정을 멈추면 관리도 멈춥니다. 매일 아침 같은 시간에 측정하면 약 복용 효과도 정확히 확인할 수 있어요. 집에 하나쯤은 있어야 하는 필수품.',
  },
  e3: {
    id: 'e3', category: 'essential', emoji: '🩸',
    name: '혈당 측정 스트립 50매',
    tagline: '식후 2시간 혈당, 지금 바로 확인',
    reason: '전당뇨 범위라면 식후 혈당 체크가 식단 선택을 바꿔요',
    price: '22,000원', priceNum: 22000,
    originalPrice: '28,000원', discountRate: 21,
    coupangUrl: 'https://www.coupang.com/np/search?q=혈당측정+스트립+50개',
    keyBenefit: '식후 혈당 스파이크 발견의 첫걸음',
    detailReason: '어떤 음식이 혈당을 올리는지 직접 데이터로 확인하면 식단 조절이 훨씬 쉬워집니다. 전당뇨 진단받으셨다면 이 스트립 하나로 식습관이 달라집니다.',
  },
  e4: {
    id: 'e4', category: 'essential', emoji: '🌬️',
    name: '삼성 공기청정기 필터 세트',
    tagline: '실내 미세먼지, 집순이에겐 더 중요해요',
    reason: '실내 공기 오염이 외부보다 2~5배 높을 수 있어요',
    price: '34,900원', priceNum: 34900,
    originalPrice: '42,000원', discountRate: 17,
    coupangUrl: 'https://www.coupang.com/np/search?q=삼성공기청정기+필터',
    keyBenefit: 'HEPA H13 등급, 바이러스까지 99.97% 차단',
    detailReason: '하루 대부분을 실내에서 보내는 집순이라면 공기 질 관리가 필수입니다. 6개월마다 필터 교체를 권장하는데 많은 분들이 잊고 사세요.',
  },
  e5: {
    id: 'e5', category: 'essential', emoji: '🧘',
    name: '요가매트 6mm TPE',
    tagline: '거실이 헬스장으로, 0원 짜리 운동 루틴',
    reason: '집에 매트 하나만 있어도 유산소+근력 모두 가능해요',
    price: '28,000원', priceNum: 28000,
    originalPrice: '35,000원', discountRate: 20,
    coupangUrl: 'https://www.coupang.com/np/search?q=요가매트+6mm+TPE',
    keyBenefit: '관절 보호 두께, 미끄럼 방지',
    detailReason: '체중 관리에는 주 3회 30분 이상의 유산소가 핵심입니다. 헬스장 없이도 매트 위에서 버피·플랭크·스쿼트로 충분한 운동이 가능해요.',
  },

  // ── Health ───────────────────────────────────────────
  h1: {
    id: 'h1', category: 'health', emoji: '🐟',
    name: '오메가3 EPA+DHA 90캡슐',
    tagline: '혈관 벽 청소부, 혈압 자연 강하',
    reason: '하루 1g 이상 EPA+DHA가 수축기 혈압을 평균 4mmHg 낮춰요',
    price: '28,900원', priceNum: 28900,
    originalPrice: '36,000원', discountRate: 20,
    coupangUrl: 'https://www.coupang.com/np/search?q=오메가3+EPA+DHA+고함량',
    keyBenefit: '혈압 강하 + 중성지방 감소',
    detailReason: '고함량 EPA+DHA(1,000mg 이상/캡슐)가 혈관 염증을 줄이고 혈압을 자연스럽게 낮춰줍니다. 혈압약을 복용 중이라면 의사와 상담 후 병행하세요.',
  },
  h2: {
    id: 'h2', category: 'health', emoji: '❤️',
    name: '코큐텐 100mg 60정',
    tagline: '심장 에너지 + 혈압 조절 동시에',
    reason: '항산화 성분 CoQ10이 혈압을 5~10mmHg 낮추는 연구 결과가 있어요',
    price: '32,000원', priceNum: 32000,
    originalPrice: '42,000원', discountRate: 24,
    coupangUrl: 'https://www.coupang.com/np/search?q=코큐텐+100mg',
    keyBenefit: '2개월 복용 시 혈압 효과 체감',
    detailReason: '코큐텐은 혈관 내피 기능을 개선해 혈압을 자연스럽게 조절합니다. 고혈압 관련 연구에서 수축기 혈압 평균 5~10mmHg 감소 효과를 보였습니다.',
  },
  h3: {
    id: 'h3', category: 'health', emoji: '🌙',
    name: '마그네슘 글리시네이트 120정',
    tagline: '혈압 조절 + 수면 질 개선 두 마리 토끼',
    reason: '마그네슘 부족 시 혈압이 오르고 수면이 얕아져요',
    price: '24,900원', priceNum: 24900,
    originalPrice: '32,000원', discountRate: 22,
    coupangUrl: 'https://www.coupang.com/np/search?q=마그네슘+글리시네이트',
    keyBenefit: '취침 전 복용으로 혈압+수면 동시 관리',
    detailReason: '현대인의 80%가 마그네슘이 부족합니다. 마그네슘은 혈관 이완을 돕고 교감신경을 안정시켜 혈압을 낮춥니다. 취침 전 300mg 복용을 권장해요.',
  },
  h4: {
    id: 'h4', category: 'health', emoji: '🌿',
    name: '베르베린 500mg 60정',
    tagline: '자연 유래 혈당 조절, 메트포르민 비교 연구까지',
    reason: '베르베린이 인슐린 민감도를 높여 혈당 스파이크를 줄여줘요',
    price: '29,500원', priceNum: 29500,
    originalPrice: '38,000원', discountRate: 22,
    coupangUrl: 'https://www.coupang.com/np/search?q=베르베린+500mg',
    keyBenefit: '전당뇨 관리의 자연 솔루션',
    detailReason: '베르베린은 인슐린 저항성을 개선하는 대표적인 천연 성분입니다. 식사 30분 전 500mg 복용 시 식후 혈당 상승폭을 유의미하게 줄여줍니다.',
  },
  h5: {
    id: 'h5', category: 'health', emoji: '🔬',
    name: '크롬 피콜리네이트 200μg',
    tagline: '탄수화물 대사 핵심 미네랄',
    reason: '크롬이 인슐린 수용체 민감도를 높여 혈당을 안정시켜요',
    price: '14,900원', priceNum: 14900,
    originalPrice: '19,000원', discountRate: 22,
    coupangUrl: 'https://www.coupang.com/np/search?q=크롬+피콜리네이트',
    keyBenefit: '탄수화물 많이 드시는 분께 권장',
    detailReason: '크롬은 인슐린 작용을 보조해 탄수화물 대사를 효율화합니다. 특히 탄수화물 위주 식사를 하시는 분들의 혈당 관리에 효과적입니다.',
  },
  h6: {
    id: 'h6', category: 'health', emoji: '💪',
    name: '유청 단백질 WPI 1kg',
    tagline: '근육 유지하며 체중 감량의 황금 비율',
    reason: '단백질은 포만감을 높여 자연스럽게 칼로리 섭취를 줄여줘요',
    price: '39,900원', priceNum: 39900,
    originalPrice: '52,000원', discountRate: 23,
    coupangUrl: 'https://www.coupang.com/np/search?q=유청단백질+WPI+1kg',
    keyBenefit: '지방 줄이고 근육은 지키기',
    detailReason: '체중 감량 중 단백질 섭취가 부족하면 근육이 빠집니다. WPI는 유당이 제거된 순수 단백질로 소화 부담 없이 체중 관리를 도와요.',
  },
  h7: {
    id: 'h7', category: 'health', emoji: '👁️',
    name: '루테인 + 지아잔틴 60정',
    tagline: '하루 종일 화면 보는 눈을 지켜드려요',
    reason: '루테인은 블루라이트 차단과 황반 변성 예방에 도움이 돼요',
    price: '22,900원', priceNum: 22900,
    originalPrice: '29,000원', discountRate: 21,
    coupangUrl: 'https://www.coupang.com/np/search?q=루테인+지아잔틴',
    keyBenefit: '화면 많이 보는 집순이 필수템',
    detailReason: '집에서 스마트폰·PC를 하루 6시간 이상 보신다면 루테인 보충이 권장됩니다. 황반 색소 밀도를 높여 장기적 시력 보호에 기여해요.',
  },
  h8: {
    id: 'h8', category: 'health', emoji: '☀️',
    name: '비타민D3+K2 90정',
    tagline: '실내 생활자의 필수 햇빛 대체재',
    reason: '실내에만 있으면 비타민D 결핍이 면역·기분에 영향을 줘요',
    price: '19,900원', priceNum: 19900,
    originalPrice: '25,000원', discountRate: 20,
    coupangUrl: 'https://www.coupang.com/np/search?q=비타민D3+K2',
    keyBenefit: '뼈·면역·기분까지 관리',
    detailReason: '국내 성인 75%가 비타민D 부족 상태입니다. 집순이라면 더 심각할 수 있어요. K2와 함께 섭취하면 칼슘 흡수 효율이 높아져 뼈 건강도 챙겨집니다.',
  },
  h9: {
    id: 'h9', category: 'health', emoji: '🦠',
    name: '프로바이오틱스 200억 30포',
    tagline: '장 건강이 면역과 체중 모두에 연결돼요',
    reason: '유익균 비율을 높이면 체지방 감소와 혈당 안정에 도움이 돼요',
    price: '27,900원', priceNum: 27900,
    originalPrice: '35,000원', discountRate: 20,
    coupangUrl: 'https://www.coupang.com/np/search?q=프로바이오틱스+200억',
    keyBenefit: '장 건강 → 면역력 → 체중 관리',
    detailReason: '장내 유익균 비율이 높을수록 체지방 분해가 잘 되고 혈당도 안정적으로 유지됩니다. 1인 가구의 불규칙한 식습관을 보완하는 기본 영양제예요.',
  },
  h10: {
    id: 'h10', category: 'health', emoji: '🌈',
    name: '종합 멀티비타민 90정',
    tagline: '한 알로 일일 영양소 기준치 완성',
    reason: '불균형한 1인 가구 식사를 영양소로 보완해줘요',
    price: '18,900원', priceNum: 18900,
    originalPrice: '24,000원', discountRate: 21,
    coupangUrl: 'https://www.coupang.com/np/search?q=멀티비타민+종합',
    keyBenefit: '매일 아침 한 알, 영양 기반 완성',
    detailReason: '1인 가구의 식단은 다양성이 부족하기 쉽습니다. 멀티비타민 하나로 23가지 영양소를 보충해 기초 에너지와 면역력을 유지하세요.',
  },
};

export function getProductById(id: string): Product | undefined {
  return PRODUCTS[id];
}
